# Generated by Django 3.2 on 2022-11-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20221015_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='usertype_id',
        ),
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Dealer', 'Dealer')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
