# Generated by Django 3.2 on 2022-10-15 07:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_for_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.IntegerField()),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('balcony', models.IntegerField()),
                ('carpet_area', models.IntegerField()),
                ('builtup_area', models.IntegerField()),
                ('superbuiltup_area', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('property_age', models.IntegerField()),
                ('property_status', models.CharField(choices=[('Ready to Move', 'Ready To Move'), ('Under Construction', 'Under Construction')], default='Ready to Move', max_length=30)),
                ('furnishing_status', models.CharField(choices=[('Unfurnished', 'Unfurnished'), ('Semi Furnished', 'Semi Furnished'), ('Fully Furnished', 'Fully Furnished')], default='Unfurnished', max_length=30)),
                ('available_for', models.CharField(choices=[('Family', 'Family'), ('Bachelors', 'Bachelors'), ('All', 'All')], default='All', max_length=30)),
                ('image', models.ImageField(upload_to='photo/property_image')),
                ('parking', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.city')),
                ('property_for_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertyfor')),
                ('property_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.propertytype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swimming_pool', models.BooleanField(default=False)),
                ('visitor_parking', models.BooleanField(default=False)),
                ('power_backup', models.BooleanField(default=False)),
                ('security_firealarm', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('fitness_centre', models.BooleanField(default=False)),
                ('childrens_park', models.BooleanField(default=False)),
                ('club_house', models.BooleanField(default=False)),
                ('multipurpose_room', models.BooleanField(default=False)),
                ('sports_facility', models.BooleanField(default=False)),
                ('rain_water_harvesting', models.BooleanField(default=False)),
                ('intercom', models.BooleanField(default=False)),
                ('maintenance_staff', models.BooleanField(default=False)),
                ('water_purifier', models.BooleanField(default=False)),
                ('vaastu_compliant', models.BooleanField(default=False)),
                ('natural_light', models.BooleanField(default=False)),
                ('wifi_connectivity', models.BooleanField(default=False)),
                ('shopping_centre', models.BooleanField(default=False)),
                ('atm', models.BooleanField(default=False)),
                ('waste_disposal', models.BooleanField(default=False)),
                ('piped_gas', models.BooleanField(default=False)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
