# Generated by Django 3.2 on 2022-10-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_features_property_propertyfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
