# Generated by Django 3.2 on 2022-10-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.propertytype'),
        ),
    ]
