# Generated by Django 3.2 on 2022-10-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20221026_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='builtup_area',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='superbuiltup_area',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
