# Generated by Django 3.2 on 2022-10-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20221029_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='balcony',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
