# Generated by Django 3.2 on 2023-01-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_property_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='photo/featured_image'),
        ),
    ]
